fork:
	gcc -Wall fork.c -o fork

fork_pc:
	gcc -Wall fork_pc.c -o fork_pc

fork_wait:
	gcc -Wall fork_wait.c -o fork_wait

fork_execv:
	gcc -Wall fork_execv.c -o fork_execv

fork_execvp:
	gcc -Wall fork_execvp.c -o fork_execvp

fork_n:
	gcc -Wall fork_n.c -o fork_n

do_nothing:
	gcc -Wall do_nothing.c -o do_nothing

time_fork_exec_wait:
	gcc -Wall time_fork_exec_wait.c -o time_fork_exec_wait
